### ISSUE TITLE
The paper

### ISSUE THREAD

**Issue by ydhongHIT** [dingmyu/HR-NAS#1]
Could you release the paper?

**Comment by dingmyu** [comment]
Hi,

As the patent application process is still in progress (on the company side), we are temporarily unable to release the paper. Once the patent application completed, we will release the paper and codes (hopefully within a few days).

Regards,
Mingyu

**Comment by dingmyu** [comment]
Hi,

The paper and code are released.
Feel free to reopen the issue if you have any further questions.

Mingyu
